comment: "Trying with fixed light settings to see if the model still works (there was no noticeable progress for varying light)"
# we should also try it with the fixed spawn to be closer to the evaluation scenario, maybe the differential can do it 

n_envs: 10
n_epochs: 5 # amount of training passes over the replay buffer per timestep

eval_settings:
  log_interval: 5
  num_evals_per_difficulty: 20
  eval_light_settings: False


batch_size: 64



n_steps: 256 # 64 # amount of steps to collect per collect_rollouts per environment
# Tensorboard shows the mean_episode_length is below 3
# we can reduce the n_steps to make the collection time shorter while still collecting a lot of games
# n_steps * fixedTimestepsLength = the amount of seconds required for the collection


copy_model_from: False #models_and_dumps/best_model_episode_70
# copy_model_from can be False or a string (filename without .zip suffix)

total_timesteps: 2500000

env_kwargs:
  jetbot: DifferentialJetBot
  spawn_point: OrientationRandom
  # spawn_point can be Fixed, OrientationRandom, OrientationVeryRandom and FullyRandom
  frame_stacking: 10
  image_preprocessing:
    downsampling_factor: 2
    grayscale: True
    equalize: True
    contrast_increase: "TODO"
    # vielleicht eine art Mode variable hier reinpacken contrast increase s equalize
    normalize_images: False
  coefficients:
    distanceCoefficient: 0.5
    orientationCoefficient: 0.0
    velocityCoefficient: 0.0
    eventCoefficient: 1.0
  trainingMapType: randomEval
  fixedTimestepsLength: 0.5
  # fixedTimestepsLength can either be False or a number (seconds that each timestep contains)
  # 2024-02-04/11-56-53 used non-fixed timesteps and had 0.4 fps per environment
  # this run achgieved the highest accuracies yet --> we can increase the duration of fixed timesteps to above a second

  width: 500 #336
  height: 168
  lighting_setting:
    # was fixed at 5 before
    low: 5 #2.5
    high: 5 #7.5

