comment: "all maps train with fixed spawn and event + distance reward possible?"

n_envs: 100
num_evals_per_difficulty: 100
n_epochs: 5 # amount of training passes oer the replay buffer per timestep
log_interval: 1
batch_size: 64
n_steps: 128 # amount of steps to collect per epoch

coefficients:

env_kwargs:
  spawn_point_random: False
  single_goal: False
  frame_stacking: 3
  image_preprocessing:
    grayscale: True
    equalize: True
    contrast_increase: "TODO"
    # vielleicht eine art Mode variable hier reinpacken contrast increase s equalize
    normalize_images: False
  coefficients:
    distanceCoefficient: 0.5
    orientationCoefficient: 0.0
    velocityCoefficient: 0.0
    eventCoefficient: 1.0
  mapType: randomEvalEasy
  width: 500 #336
  height: 168


