comment: "replay only linux"

n_envs: 1
copy_model_from: False

total_timesteps: 5000000

seed: 2048

eval_settings:
  n_eval_episodes: 100
  eval_light_settings: True
  eval_only: False
  number_eval_runs: 1

episode_record_replay_settings:
  deterministic_sampling: True
  replay_folder: episode_recordings/hardDistanceMixedLight_recordings_without_videos
  # replay_folder can be False to replay the previously recorded episodes

algo_settings:
  n_epochs: 5


  batch_size: 64

  n_steps: 512

  policy: "CnnPolicy"
  use_bundled_calls: True
  use_fresh_obs: False

  print_network_and_loss_structure: False

  net_arch:
    pi: []
    vf: []


env_kwargs:
  use_unity: False
  jetBotName: DifferentialJetBot
  spawnOrientation: Random
  frame_stacking: 10
  image_preprocessing:
    downsampling_factor: 2
    grayscale: True
    equalize: True
  coefficients:
    distanceCoefficient: 1
    orientationCoefficient: 0
    velocityCoefficient: 0
    eventCoefficient: 0
  collisionMode: oncePerTimestep
  # unrestricted, oncePerTimestep, oncePerEpisode, resetUponCollision, ignoreCollisions
  trainingMapType: randomEvalMedium
  trainingLightSetting: random
  # random, bright, standard, dark
  fixedTimestepsLength: 0.3

  agentImageWidth: 500
  agentImageHeight: 168

