comment: "Copy of the best yet seen configs from 19.02.2024"


eval_settings:
  log_interval: 5
  n_eval_episodes: 20
  eval_light_settings: True

print_network_and_loss_structure: False


n_envs: 10
n_epochs: 5 # amount of training passes over the replay buffer per timestep


batch_size: 64

n_steps: 1024 
# amount of steps to collect per collect_rollouts per environment
# Tensorboard shows the mean_episode_length is below 3
# we can reduce the n_steps to make the collection time shorter while still collecting a lot of episodes
# n_steps * fixedTimestepsLength = the amount of seconds required for the collection


copy_model_from: False #models_and_dumps/best_model_episode_70
# copy_model_from can be False or a string (filename without .zip suffix)

total_timesteps: 2500000 # restricted to 650000 due to real time limit (about 5 hours per training)

seed: 2048

policy: "CnnPolicy"
use_bundled_calls: True
use_fresh_obs: False
eval_only: False
number_eval_runs: 3

net_arch:
  pi: []
  vf: []

env_kwargs: 
  jetBotName: DifferentialJetBot
  spawnOrientation: OrientationRandom
  frame_stacking: 10
  image_preprocessing: 
    downsampling_factor: 1
    grayscale: True
    equalize: True
    contrast_increase: "TODO"
    normalize_images: False
  coefficients: 
    distanceCoefficient: 0.5
    orientationCoefficient: 0.0
    velocityCoefficient: 0.0
    eventCoefficient: 1.0 
  trainingMapType: randomEval
  trainingLightSetting: standard
  fixedTimestepsLength: 0.3
  width: 500
  height: 168